

const DataTypes = require('sequelize').DataTypes;

module.exports = (sequelize) => {
    const character = sequelize.define("character",
        {
            Id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
            AccountId: { type: DataTypes.INTEGER, defaultValue: 0 },
            Act4Dead: { type: DataTypes.INTEGER, defaultValue: 0 },
            Act4Kill: { type: DataTypes.INTEGER, defaultValue: 0 },
            Act4Points: { type: DataTypes.INTEGER, defaultValue: 0 },
            ArenaWinner: { type: DataTypes.INTEGER, defaultValue: 0 },
            Biography: { type: DataTypes.STRING, defaultValue: '' },
            BuffBlocked: { type: DataTypes.BOOLEAN, defaultValue: false},
            Class: { type: DataTypes.INTEGER, defaultValue: 0 },
            Compliment: { type: DataTypes.INTEGER, defaultValue: 0 },
            Dignity: { type: DataTypes.FLOAT, defaultValue: 0 },
            EmoticonsBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
            ExchangeBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
            Faction: { type: DataTypes.INTEGER, defaultValue: 0 },
            FamilyRequestBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
            FriendRequestBlocked: { type: DataTypes.BOOLEAN, defaultValue: false},
            
            Gender: { type: DataTypes.INTEGER, defaultValue: 0 },
            Gold: { type: DataTypes.INTEGER, defaultValue: 0 },
            GroupRequestBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
            HairColor: { type: DataTypes.INTEGER, defaultValue: 0 },
            HairStyle: { type: DataTypes.INTEGER, defaultValue: 0 },
            HeroChatBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },

            HeroLevel: { type: DataTypes.INTEGER, defaultValue: 0 },
            HeroXp: { type: DataTypes.INTEGER, defaultValue: 0 },

            Hp: { type: DataTypes.INTEGER, defaultValue: 0 },
            HpBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
            IsPetAutoRelive: { type: DataTypes.BOOLEAN, defaultValue: false },
            IsPartnerAutoRelive: { type: DataTypes.BOOLEAN, defaultValue: false },
            JobLevel: { type: DataTypes.INTEGER, defaultValue: 0 },
            JobLevelXp: { type: DataTypes.INTEGER, defaultValue: 0 },
            
            Level: { type: DataTypes.INTEGER, defaultValue: 0 },
            LevelXp: { type: DataTypes.INTEGER, defaultValue: 0 },

            MapId: { type: DataTypes.INTEGER, defaultValue: 0 },
            MapX: { type: DataTypes.INTEGER, defaultValue: 0 },
            MapY: { type: DataTypes.INTEGER, defaultValue: 0 },
            MasterPoints: { type: DataTypes.INTEGER, defaultValue: 0 },
            MasterTicket: { type: DataTypes.INTEGER, defaultValue: 0 },
            MaxPartnerCount: { type: DataTypes.INTEGER, defaultValue: 0 },
            MaxPetCount: { type: DataTypes.INTEGER, defaultValue: 0 },
            MinilandInviteBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
            MinilandMessage: { type: DataTypes.STRING, defaultValue: '' },
            MinilandPoint: { type: DataTypes.INTEGER, defaultValue: 0 },
            MinilandState: { type: DataTypes.INTEGER, defaultValue: 0 },
            MouseAimLock: { type: DataTypes.BOOLEAN, defaultValue: false },
            Mp: { type: DataTypes.INTEGER },
            Prefix: { type: DataTypes.STRING, defaultValue: '' },

            Name: { type: DataTypes.STRING, defaultValue: ''},
            QuickGetUp: { type: DataTypes.BOOLEAN, defaultValue: false },
            HideHat: { type: DataTypes.BOOLEAN, defaultValue: false },
            UiBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
            RagePoint: { type: DataTypes.INTEGER, defaultValue: 0 },

            Reput: { type: DataTypes.INTEGER, defaultValue: 0 },
            Slot: { type: DataTypes.INTEGER, defaultValue: 0 },
            SpPointsBonus: { type: DataTypes.INTEGER, defaultValue: 0 },
            SpPointsBasic: { type: DataTypes.INTEGER, defaultValue: 0 },
            TalentLose: { type: DataTypes.INTEGER, defaultValue: 0 },
            TalentSurrender: { type: DataTypes.INTEGER, defaultValue: 0 },
            TalentWin: { type: DataTypes.INTEGER, defaultValue: 0 },
            WhisperBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
            Act5RespawnType: { type: DataTypes.INTEGER, defaultValue: 0 },
            PartnerInventory: { type: DataTypes.JSONB },
            NosMates: { type: DataTypes.JSONB },
            PartnerWarehouse: { type: DataTypes.JSONB },
            Bonus: { type: DataTypes.JSONB }, 
            StaticBuffs: { type: DataTypes.JSONB },
            Quicklist: { type: DataTypes.JSONB },
            LearnedSkills: { type: DataTypes.JSONB },
            Titles: { type: DataTypes.JSONB },
            CompletedScripts: { type: DataTypes.JSONB },
            CompletedQuests: { type: DataTypes.JSONB },
            ActiveQuests: { type: DataTypes.JSONB },
            CompletedPeriodicQuests: { type: DataTypes.JSONB },
            MinilandObjects: { type: DataTypes.JSONB },
            ReturnPoint: { type: DataTypes.JSONB },
            Inventory: { type: DataTypes.JSONB },
            EquippedStuffs: { type: DataTypes.JSONB },
            LifetimeStats: { type: DataTypes.JSONB },
            RespawnType: { type: DataTypes.INTEGER, defaultValue: 0 },
            CompletedTimeSpaces: { type: DataTypes.JSONB }, 
            RaidRestrictionDto: { type: DataTypes.JSONB }, 
            RainbowBattleLeaverBusterDto: { type: DataTypes.JSONB },
            //CanRename: { type: DataTypes.BOOLEAN, defaultValue: false },
            //CharacterPity: { type: DataTypes.JSONB },
            //CharacterBoxPity: { type: DataTypes.JSONB },
            //HomeWarps: { type: DataTypes.JSONB },
            //RaidRecord: { type: DataTypes.JSONB },
            //BattlePassItemDto: { type: DataTypes.JSONB },
            //BattlePassOptionDto: { type: DataTypes.JSONB },
            //BattlePassQuestDto: { type: DataTypes.JSONB },
            //MaxStarTrainerDto: { type: DataTypes.JSONB },
            //TrainerQuestDto: { type: DataTypes.JSONB },
            CreatedAt: { type: DataTypes.DATE, defaultValue: new Date(Date.now())},
            UpdatedAt: { type: DataTypes.DATE, defaultValue: new Date(Date.now())},
            DeletedAt: { type: DataTypes.DATE, defaultValue: new Date(Date.now())},
        }, {
        timestamps: false,
        schema: "characters"
    });
    return character;
} 

